// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppConnectionInformationUpdate { user: string | null, password: string | null, database: string | null, host: string | null, port: number | null, }