// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConnectionInformation } from "./AppConnectionInformation";
import type { ConnectionEnvironment } from "./ConnectionEnvironment";

export interface AppConnection { id: string, name: string, environment: ConnectionEnvironment, connection_information: AppConnectionInformation, }