// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface AppConnectionInformation { user: string, password: string, database: string, host: string, port: number, }