// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AppConnectionInformationUpdate } from "./AppConnectionInformationUpdate";
import type { ConnectionEnvironment } from "./ConnectionEnvironment";

export interface InvokeUpdateConnection { id: string, name: string | null, environment: ConnectionEnvironment | null, connection_information: AppConnectionInformationUpdate | null, }