// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { QueryColumn } from "./QueryColumn";

export interface InvokeExecuteQueryReturn { columns: Array<QueryColumn>, rows: Record<string, unknown>[], }